sudo: false
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.cache"

deploy:
  provider: packagecloud
  repository: riak-mdc-mon
  username: $PACKAGECLOUD_USER
  token: $PACKAGECLOUD_TOKEN
  skip_cleanup: true
  on:
    branch: master
