sudo: false
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.cache"

before_deploy: 
  - export RELEASE_PKG_FILE=$(ls *.tar.gz)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
deploy:
  provider: releases
  api-key: $GITHUB_OATH_TOKEN
  file_glob: true
  file: "${RELEASE_PKG_FILE}" 
  skip_cleanup: true
  on:
    tags: true
