sudo: false
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.cache"

deploy:
  provider: releases
  api-key: $GITHUB_OATH_TOKEN
  file: *.tar.gz
  skip_cleanup: true
  file_glob: true
  on:
    tags: true
